// <auto-generated />
namespace TestApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Type_ServicePation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Type_ServicePation));
        
        string IMigrationMetadata.Id
        {
            get { return "201812250845432_Type_Service-Pation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
