// <auto-generated />
namespace TestApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class book2Publishergetter4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(book2Publishergetter4));
        
        string IMigrationMetadata.Id
        {
            get { return "201906170903268_book2-Publisher-getter4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
